import { Component, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { EmiService } from '../../../core/services/emi.service';
import { LoanService } from '../../../core/services/loan.service';
import { AuthService } from '../../../core/services/auth.service';
import { EmiScheduleResponse } from '../../../core/models/emi.model';
import { LoanResponse } from '../../../core/models/loan.model';

@Component({
  selector: 'app-repayment',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-header">
      <h1 class="page-title">Repayment Schedule</h1>
      <p class="page-subtitle">Reducing-balance EMI after moratorium · Pay EMI · View penalties</p>
    </div>

    @if (loading()) {
      <div class="flex justify-center py-16"><span class="spinner w-8 h-8"></span></div>
    } @else if (!loan()) {
      <div class="card text-center py-10 text-slate-500">No loan in repayment phase found.</div>
    } @else {
      <div class="max-w-4xl">
        @if (emis().length > 0) {
          <div class="card mb-4 bg-primary-50 border-primary-100">
            <p class="text-sm text-slate-600">
              Computed on capitalised principal
              <span class="font-bold text-primary-800 ml-1">{{ inr(loan()!.outstandingBalance) }}</span>
              · reducing balance · {{ loan()!.interestRate }}% p.a.
            </p>
          </div>
        }

        @if (emis().length === 0) {
          <div class="card text-center py-10 text-slate-500">
            <p>No EMI schedule generated yet.</p>
            <p class="text-xs mt-2 text-slate-400">EMI schedule is generated by the manager after loan sanction.</p>
          </div>
        } @else {
          <div class="table-wrapper">
            <table class="ts-table">
              <thead><tr>
                <th>EMI #</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>Principal</th>
                <th>Interest</th>
                <th>Penalty</th>
                <th>Status</th>
                <th></th>
              </tr></thead>
              <tbody>
                @for (e of emis(); track e.emiId) {
                  <tr [class]="e.status === 'OVERDUE' ? 'bg-red-50' : ''">
                    <td class="font-medium">{{ e.emiNumber }}</td>
                    <td>{{ fmtDate(e.dueDate) }}</td>
                    <td class="font-semibold">{{ inr(e.emiAmount) }}</td>
                    <td>{{ inr(e.principalPart) }}</td>
                    <td>{{ inr(e.interestPart) }}</td>
                    <td [class]="e.penaltyAmount > 0 ? 'text-red-600 font-medium' : 'text-slate-300'">
                      {{ e.penaltyAmount > 0 ? inr(e.penaltyAmount) : '—' }}
                    </td>
                    <td>
                      <span [class]="statusBadge(e.status)" class="badge">{{ e.status }}</span>
                    </td>
                    <td>
                      @if (e.status === 'DUE' || e.status === 'OVERDUE') {
                        <button class="btn-primary text-xs py-1.5 px-3"
                                [disabled]="paying() === e.emiId"
                                (click)="pay(e)">
                          @if (paying() === e.emiId) { <span class="spinner w-3 h-3"></span> }
                          Pay
                        </button>
                      }
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>

          <div class="info-bar mt-4 text-xs">
            ℹ️ Late payment adds a {{ loan()!.interestRate }}% penalty on the overdue EMI.
          </div>
        }
      </div>
    }
  `
})
export class RepaymentComponent implements OnInit {
  loan = signal<LoanResponse | null>(null);
  emis = signal<EmiScheduleResponse[]>([]);
  loading = signal(true);
  paying = signal<number | null>(null);

  constructor(private emiSvc: EmiService, private loanSvc: LoanService, private auth: AuthService) {}

  ngOnInit() {
    const uid = this.auth.currentUser()?.id;
    if (!uid) { this.loading.set(false); return; }
    this.loanSvc.getLoansByBorrower(uid).subscribe(res => {
      const loan = res.data?.find((l: LoanResponse) => ['REPAYMENT', 'ACTIVE', 'MORATORIUM'].includes(l.status));
      if (!loan) { this.loading.set(false); return; }
      this.loan.set(loan);
      this.emiSvc.getScheduleByLoan(loan.loanId).subscribe(r => {
        this.emis.set(r.data ?? []);
        this.loading.set(false);
      });
    });
  }

  pay(emi: EmiScheduleResponse) {
    if (!this.loan()) return;
    this.paying.set(emi.emiId);
    this.emiSvc.payEmi(this.loan()!.loanId, emi.emiId, {
      paidAmount:    emi.emiAmount + (emi.penaltyAmount ?? 0),
      paidOn:        new Date().toISOString().split('T')[0],
      paymentMethod: 'ONLINE'
    }).subscribe({
      next: res => {
        this.emis.update(list => list.map(e => e.emiId === emi.emiId ? res.data : e));
        this.paying.set(null);
      },
      error: () => this.paying.set(null)
    });
  }

  inr(v: number) { return '₹' + (v ?? 0).toLocaleString('en-IN'); }
  fmtDate(d: string) {
    if (!d) return '—';
    return new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  }
  statusBadge(s: string) {
    return { PAID: 'badge-green', DUE: 'badge-amber', UPCOMING: 'badge-slate', OVERDUE: 'badge-red' }[s] ?? 'badge-slate';
  }
}
